package com.Carleasing.carleasing.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "CustomerDetail")
public class Customer implements Serializable {
    @DynamoDBHashKey(attributeName = "customerId")
    @DynamoDBAutoGeneratedKey
    private String customerId;
    @DynamoDBAttribute
    private String leaseNo;
    @DynamoDBAttribute
    private Person person;
    @DynamoDBAttribute
    private Address address;
    @DynamoDBAttribute
    private long SSN;
    @DynamoDBAttribute
    private int creditScore;

}
