package com.Carleasing.carleasing.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@DynamoDBDocument
@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "LeasingOrder")
public class Order {
    @DynamoDBHashKey(attributeName = "leasingId")
    @DynamoDBAutoGeneratedKey
    private String leasingId;
    @DynamoDBAttribute
    private String firstName;
    @DynamoDBAttribute
    private String lastName;
    @DynamoDBAttribute
    private String Address;
    @DynamoDBAttribute
    private int creditScore;
    @DynamoDBAttribute
    private String carDetails;
    @DynamoDBAttribute
    private int period;
    @DynamoDBAttribute
    private String plan;
    @DynamoDBAttribute
    private String style;
    @DynamoDBAttribute
    private int quantity;
    @DynamoDBAttribute
    private Long ssn;
    @DynamoDBAttribute
    private double value;
    @DynamoDBAttribute
    private double leasePrice;
    @DynamoDBAttribute
    private String make;
    @DynamoDBAttribute
    private String model;
    @DynamoDBAttribute
    private String year;
    @DynamoDBAttribute
    private String trimLevel;
    @DynamoDBAttribute
    private String color;
    @DynamoDBAttribute
    private String regNo;
}
