package com.Carleasing.carleasing.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@DynamoDBDocument
@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "VehicleDetails")
public class Vehicle {

    @DynamoDBHashKey(attributeName = "makeId")
    private String makeId;
    @DynamoDBRangeKey(attributeName = "vehicleId")
    @DynamoDBAutoGeneratedKey
    private String vehicleId;
    @DynamoDBAttribute
    private String make;
    @DynamoDBAttribute
    private String model;
    @DynamoDBAttribute
    private String style;
    @DynamoDBAttribute
    private Long year;
    @DynamoDBAttribute
    private String trimLevel;
    @DynamoDBAttribute
    private String color;
    @DynamoDBAttribute
    private Long odometer;
    @DynamoDBAttribute
    private String regNo;
    @DynamoDBAttribute
    private double carValue;
    @DynamoDBAttribute
    private String carImage;
    @DynamoDBAttribute
    private String imageName;
    @DynamoDBAttribute
    private CarMake carMake;
}
