package com.Carleasing.carleasing.LeaseLambda;

import com.Carleasing.carleasing.model.Customer;
import com.Carleasing.carleasing.model.Vehicle;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "LeasingDetails")
public class LeaseLambdaRequest {
    @DynamoDBHashKey(attributeName = "customerId")
    @DynamoDBAutoGeneratedKey
    private String leasingNo;
    @DynamoDBAttribute
    private Customer customer;
    @DynamoDBAttribute
    private String SSN;
    @DynamoDBAttribute
    private int creditScore;
    @DynamoDBAttribute
    private Vehicle vehicle;
    @DynamoDBAttribute
    private String make;
    @DynamoDBAttribute
    private String style;
    @DynamoDBAttribute
    private int period;
    @DynamoDBAttribute
    private int quantity;
    @DynamoDBAttribute
    private String plan;
}
